// Shared by the importer and the browser so every prepared family has a control.
export const OSM_PROFILE_VERSION = 2;
export const OSM_CATEGORIES = /** @type {const} */ ([
  {
    id: 'roads',
    layer: 'roads',
    keys: ['highway'],
    name: 'Roads, paths & trails',
    description: 'Streets, footways, cycleways, tracks and highway features',
    zoom: 6,
    color: '#eacb94',
  },
  {
    id: 'railways',
    layer: 'roads',
    keys: ['railway'],
    name: 'Railways',
    description: 'Rail, tram, subway tracks and railway features',
    zoom: 12,
    color: '#e6aeb5',
  },
  {
    id: 'aerialways',
    layer: 'details',
    keys: ['aerialway'],
    name: 'Cable cars & lifts',
    description: 'Cableways, chairlifts and stations',
    zoom: 17,
    color: '#f0c582',
  },
  {
    id: 'aviation',
    layer: 'details',
    keys: ['aeroway'],
    name: 'Airports & aviation',
    description: 'Runways, taxiways, helipads and airport facilities',
    zoom: 17,
    color: '#babcf4',
  },
  {
    id: 'transit',
    layer: 'details',
    keys: ['public_transport'],
    name: 'Public transport',
    description: 'Stops, platforms and stations',
    zoom: 17,
    color: '#f1be76',
  },
  {
    id: 'routes',
    layer: 'details',
    keys: ['route'],
    name: 'Tagged routes',
    description:
      'Ferry and other directly tagged route geometry; relation itineraries are not assembled',
    zoom: 17,
    color: '#edb37e',
  },
  {
    id: 'water',
    layer: 'water',
    keys: ['water'],
    name: 'Lakes & water areas',
    description: 'Lakes, ponds, reservoirs and riverbanks',
    zoom: 8,
    color: '#63bcea',
  },
  {
    id: 'waterways',
    layer: 'water',
    keys: ['waterway'],
    name: 'Rivers, streams & waterways',
    description: 'Rivers, canals, streams and waterway structures',
    zoom: 12,
    color: '#80d3f2',
  },
  {
    id: 'landuse',
    layer: 'land',
    keys: ['landuse'],
    name: 'Land use',
    description:
      'Residential, commercial, farmland, forest and industrial areas',
    zoom: 10,
    color: '#71bb91',
  },
  {
    id: 'landcover',
    layer: 'land',
    keys: ['landcover'],
    name: 'Land cover',
    description: 'Vegetation and other tagged surface cover',
    zoom: 10,
    color: '#a0c27a',
  },
  {
    id: 'natural',
    layer: 'land',
    keys: ['natural'],
    name: 'Natural features',
    description: 'Woods, wetlands, beaches, cliffs, peaks and trees',
    zoom: 10,
    color: '#91c99a',
  },
  {
    id: 'leisure',
    layer: 'land',
    keys: ['leisure'],
    name: 'Parks, recreation & leisure',
    description: 'Parks, playgrounds, pitches, marinas and leisure facilities',
    zoom: 10,
    color: '#a7db88',
  },
  {
    id: 'boundaries',
    layer: 'land',
    keys: ['boundary'],
    name: 'Boundaries',
    description: 'Administrative, protected-area and other tagged boundaries',
    zoom: 10,
    color: '#cca1e5',
  },
  {
    id: 'buildings',
    layer: 'buildings',
    keys: ['building', 'building:part'],
    name: 'Building footprints',
    description: 'Buildings and building parts',
    zoom: 16,
    color: '#dbc3a6',
  },
  {
    id: 'places',
    layer: 'places',
    keys: ['place'],
    name: 'Place names',
    description: 'Cities, towns, villages, neighborhoods and named places',
    zoom: 8,
    color: '#f3f1df',
  },
  {
    id: 'amenities',
    layer: 'details',
    keys: ['amenity'],
    name: 'Amenities & services',
    description:
      'Restaurants, cafes, schools, parking, toilets, banks and civic facilities',
    zoom: 17,
    color: '#ceadf4',
  },
  {
    id: 'shops',
    layer: 'details',
    keys: ['shop'],
    name: 'Shops',
    description: 'Supermarkets, retail stores and specialist shops',
    zoom: 17,
    color: '#edabd7',
  },
  {
    id: 'healthcare',
    layer: 'details',
    keys: ['healthcare'],
    name: 'Healthcare',
    description:
      'Clinics, doctors and other healthcare-tagged facilities; hospitals may also appear under amenities',
    zoom: 17,
    color: '#f3a7aa',
  },
  {
    id: 'tourism',
    layer: 'details',
    keys: ['tourism'],
    name: 'Tourism & accommodation',
    description: 'Hotels, camp sites, museums, attractions and viewpoints',
    zoom: 17,
    color: '#dab2ee',
  },
  {
    id: 'historic',
    layer: 'details',
    keys: ['historic'],
    name: 'Historic features',
    description: 'Monuments, ruins, memorials and heritage sites',
    zoom: 17,
    color: '#dfbe99',
  },
  {
    id: 'power',
    layer: 'details',
    keys: ['power'],
    name: 'Power infrastructure',
    description: 'Power lines, pylons, substations and generators',
    zoom: 17,
    color: '#efd577',
  },
  {
    id: 'telecom',
    layer: 'details',
    keys: ['telecom'],
    name: 'Telecommunications',
    description:
      'Telecom-tagged infrastructure; towers may also appear under man-made features',
    zoom: 17,
    color: '#93d0df',
  },
  {
    id: 'structures',
    layer: 'details',
    keys: ['man_made'],
    name: 'Man-made features',
    description:
      'Purple eye: surveillance. Red hammer: other structures, including towers, piers and pipelines.',
    zoom: 17,
    color: '#ff555f',
  },
  {
    id: 'barriers',
    layer: 'details',
    keys: ['barrier'],
    name: 'Barriers & gates',
    description: 'Fences, walls, gates and bollards',
    zoom: 17,
    color: '#e1b4a4',
  },
  {
    id: 'emergency',
    layer: 'details',
    keys: ['emergency'],
    name: 'Emergency equipment',
    description: 'Fire hydrants, defibrillators and emergency facilities',
    zoom: 17,
    color: '#f5a097',
  },
  {
    id: 'craft',
    layer: 'details',
    keys: ['craft'],
    name: 'Crafts & trades',
    description: 'Workshops, tradespeople and craft businesses',
    zoom: 17,
    color: '#d7bd96',
  },
  {
    id: 'offices',
    layer: 'details',
    keys: ['office'],
    name: 'Offices',
    description: 'Business, professional, government and nonprofit offices',
    zoom: 17,
    color: '#adc5ed',
  },
  {
    id: 'military',
    layer: 'details',
    keys: ['military'],
    name: 'Military features',
    description: 'Publicly mapped military facilities and areas',
    zoom: 17,
    color: '#c5bd92',
  },
  {
    id: 'geology',
    layer: 'details',
    keys: ['geological'],
    name: 'Geological features',
    description: 'Geological formations and outcrops',
    zoom: 17,
    color: '#d2ae8c',
  },
  {
    id: 'entrances',
    layer: 'details',
    keys: ['entrance'],
    name: 'Entrances',
    description: 'Mapped building and site entrances',
    zoom: 17,
    color: '#e7c9a7',
  },
  {
    id: 'addresses',
    layer: 'details',
    keys: ['addr:housenumber', 'addr:interpolation'],
    name: 'Addresses',
    description: 'House numbers and address interpolation ways',
    zoom: 17,
    color: '#efcdab',
  },
  {
    id: 'sports',
    layer: 'details',
    keys: ['sport'],
    name: 'Sports',
    description: 'Facilities tagged for specific sports',
    zoom: 17,
    color: '#abdca5',
  },
  {
    id: 'clubs',
    layer: 'details',
    keys: ['club'],
    name: 'Clubs',
    description: 'Sports, social and interest clubs',
    zoom: 17,
    color: '#b5bbed',
  },
  {
    id: 'indoor',
    layer: 'details',
    keys: ['indoor'],
    name: 'Indoor features',
    description: 'Mapped rooms, corridors and indoor areas shown in plan view',
    zoom: 17,
    color: '#c2b8d6',
  },
  {
    id: 'advertising',
    layer: 'details',
    keys: ['advertising'],
    name: 'Advertising',
    description: 'Billboards, signs and advertising structures',
    zoom: 17,
    color: '#efb9ca',
  },
  {
    id: 'traffic',
    layer: 'details',
    keys: ['traffic_calming', 'traffic_sign'],
    name: 'Traffic signs & calming',
    description: 'Tagged signs, speed humps and traffic-calming devices',
    zoom: 17,
    color: '#e8c582',
  },
]);
